import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import Navbar from "./components/navbar";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>winter-homework</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>
    </div>
  );
};

export default Home;
