import type { NextPage } from "next";
import Head from "next/head";
import NftCard from "./components/nftCard";
import { walletEntryPlugin } from "@particle-network/wallet";

const projectId = "d9711726-29d4-4693-b8b3-ba7d97a6ad43";
const clientKey = "cBiUsHpenqGTyxX9vcwcZv7tPPk7KBlyM7cBynV5";
const appId = "a0d294a7-1650-4e86-aab3-8f2ad5240628";
walletEntryPlugin.init({
  projectId,
  clientKey,
  appId,
});
walletEntryPlugin.walletEntryCreate();

const Home: NextPage = () => {

  return (
    <div>
      <Head>
        <title>winter-homework</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <div className="mt-8 grid grid-cols-3 ">
        <NftCard />
        <NftCard />
        <NftCard />
        <NftCard />
        <NftCard />
      </div>
    </div>
  );
};

export default Home;
